- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
     Render configuration for 802.1x voice interfaces'
  ansible.builtin.template:
    src: templates/cat1/voice_interfaces.j2
    dest: "/tmp/{{ inventory_hostname }}_voice_interface.cfg"
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_voice_ports }}"
  loop_control:
    loop_var: show_item
  register: voice8021x

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
     Create clean configuration string'
  ansible.builtin.set_fact:
    voice_config: |
      {% for result in voice8021x.results %}
      {% for line in result.stdout[0].splitlines() %}
      {% if line.strip() and line.strip() != '!' %}{{ line.strip() }}
      {% endif %}
      {% endfor %}
      {% endfor %}
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
     Trim final result'
  ansible.builtin.set_fact:
   combined_voice_config: "{{ voice_config | trim }}"
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
     DIFF'
  ansible.utils.fact_diff:
    before: "{{ combined_voice_config }}"
    after: "{{ lookup('file', '/tmp/{{ inventory_hostname }}_voice_interface.cfg') | trim }}"
  delegate_to: localhost
  diff: true
  register: voice_diff_result
  changed_when: voice_diff_result.diff_text | regex_findall('^\\+[^+].*$', multiline=True) 
  notify: "cat1_cisc_l2_000020_voice_Fail"

- name: >
   'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Step: 1 | Verify that 802.1x authentication is configured on the VOICE switch ports
    Trigger handler if NO DIFF occurred'
  debug:
    msg: "No changes detected, notifying handler that Rule ID: SV-220649r863283 Passed"
  # Trigger this only if the previous task did NOT change
  when: not voice_diff_result.changed
  changed_when: true
  notify: "cat1_cisc_l2_000020_voice_Pass"
