---
# CISC-L2-000020 - 802.1X Port-Based Authentication Evaluation
# This task verifies that 802.1X authentication is configured on all host-facing access ports.

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the ACCESS switch ports
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_access_ports }}"
  loop_control:
    loop_var: show_item
  register: access8021x

- name: >
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 1 | Verify that 802.1x authentication is configured on the ACCESS switch ports
     Create clean configuration string'
  ansible.builtin.set_fact:
    missing_8021x_interfaces: >-
      {{ access8021x.results | 
         selectattr('stdout', 'defined') | 
         rejectattr('stdout.0', 'search', 'authentication port-control auto') | 
         map(attribute='show_item.name') | list 
         + 
         access8021x.results | 
         selectattr('stdout', 'defined') | 
         rejectattr('stdout.0', 'search', 'dot1x pae authenticator') | 
         map(attribute='show_item.name') | list 
         | unique }}
  register: access_result
  changed_when: missing_8021x_interfaces | length > 0
  notify: "cat1_cisc_l2_000020_access_Fail"

- name: "STIG | Show findings | 8021x | Access"
  ansible.builtin.debug:
    msg: "The following interfaces are non-compliant: {{ missing_8021x_interfaces }}"
  when: missing_8021x_interfaces | length > 0

- name: >
   'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Step: 1 | Verify that 802.1x authentication is configured on the ACCESS switch ports
    Trigger handler if NO compliance violation occurred'
  debug:
    msg: "No changes detected, notifying handler that Rule ID: SV-220649r863283 Passed"
  # Trigger this only if the previous task did NOT change
  when: not access_result.changed
  changed_when: true
  notify: "cat1_cisc_l2_000020_access_Pass"

