---
- name: Import Stig Viewer handlers
  ansible.builtin.import_tasks: stig_viewer.yml
  when: stig_viewer == true

- name: Import Remediation handlers
  ansible.builtin.import_tasks: remediation.yml
