---
- name: Import CAT1 handlers
  ansible.builtin.import_tasks: cat1.yml

#- name: Import CAT2 handlers
#  ansible.builtin.import_tasks: cat2.yml

#- name: Import CAT3 handlers
#  ansible.builtin.import_tasks: cat3.yml
