---

# Cat1

- name: "Handler | CAT1 | SV-220649 | Auth | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_auth: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
   - "cat1_cisc_l2_000020_auth_Fail"

- name: "Handler | CAT1 | SV-220649 | Access | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_access: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
   - "cat1_cisc_l2_000020_access_Fail"
   
- name: "Handler | CAT1 | SV-220649 | Voice | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_voice: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
   - "cat1_cisc_l2_000020_voice_Fail"

- name: "Handler | CAT1 | SV-220649 | Auth | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_auth: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat1_cisc_l2_000020_auth_Pass"

- name: "Handler | CAT1 | SV-220649 | Access | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_access: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat1_cisc_l2_000020_access_Pass"

- name: "Handler | CAT1 | SV-220649 | Voice | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220649r863283_remediate_voice: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat1_cisc_l2_000020_voice_Pass"

  # Cat2

- name: "Handler | CAT2 | SV-220650 | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220650r539671_remediate_vtp: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: "cat2_cisc_l2_000030_Fail"

- name: "Handler | CAT2 | SV-220650 | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220650r539671_remediate_vtp: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: "cat2_cisc_l2_000030_Pass"

- name: "Handler | CAT2 | SV-220651 | QoS | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_qos: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen:
    - "cat2_cisc_l2_000040_Fail"

- name: "Handler | CAT2 | SV-220651 | Access | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_access: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen:
    - "cat2_cisc_l2_000040_access_Fail"

- name: "Handler | CAT2 | SV-220651 | Voice | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_voice: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen:
    - "cat2_cisc_l2_000040_voice_Fail"

- name: "Handler | CAT2 | SV-220651 | Trunk | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_trunk: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen:
    - "cat2_cisc_l2_000040_trunk_Fail"

- name: "Handler | CAT2 | SV-220651 | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000040_Pass"
    - "cat2_cisc_l2_000040_access_Pass"
    - "cat2_cisc_l2_000040_voice_Pass"
    - "cat2_cisc_l2_000040_trunk_Pass"

- name: "Handler | CAT2 | SV-220651 | QoS | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_qos: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000040_Pass"

- name: "Handler | CAT2 | SV-220651 | Access | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_access: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000040_access_Pass"

- name: "Handler | CAT2 | SV-220651 | Voice | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_voice: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000040_voice_Pass"

- name: "Handler | CAT2 | SV-220651 | Trunk | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220651r1107171_remediate_trunk: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000040_trunk_Pass" 

- name: "Handler | CAT2 | SV-220656 | Access | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220656r856278_remediate_access: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000100_access_Fail"

- name: "Handler | CAT2 | SV-220656 | Voice | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220656r856278_remediate_voice: true"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000100_voice_Fail"

- name: "Handler | CAT2 | SV-220656 | Access | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220656r856278_remediate_access: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000100_access_Pass"

- name: "Handler | CAT2 | SV-220656 | Voice | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220656r856278_remediate_voice: false"
    create: yes
    mode: '0644'
  delegate_to: localhost
  listen: 
    - "cat2_cisc_l2_000100_voice_Pass"

- name: "Handler | CAT2 | SV-220657 | STP Loop Guard | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220631r539671_remediate_loop: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000110_Fail"

- name: "Handler | CAT2 | SV-220657 | STP Loop Guard | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220631r539671_remediate_loop: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000110_Pass"

- name: "Handler | CAT2 | SV-220658 | UUFB | Access | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220658r856280_remediate_access: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000120_access_Fail"

- name: "Handler | CAT2 | SV-220658 | UUFB | Voice | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220658r856280_remediate_voice: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000120_voice_Fail"

- name: "Handler | CAT2 | SV-220658 | UUFB | Access | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220658r856280_remediate_access: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000120_access_Pass"

- name: "Handler | CAT2 | SV-220658 | UUFB | Voice | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220658r856280_remediate_access: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000120_voice_Pass"

- name: "Handler | CAT2 | SV-220659 | DHCP Snooping | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220659r928999_remediate_dhcp: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000130_Fail"

- name: "Handler | CAT2 | SV-220659 | DHCP Snooping | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220659r928999_remediate_dhcp: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000130_Pass"

- name: "Handler | CAT2 | SV-220660 | IP Source Guard | Access | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220660r929001_remediate_access: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000140_access_Fail"

- name: "Handler | CAT2 | SV-220660 | IP Source Guard | Access | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220660r929001_remediate_access: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000140_access_Pass"

- name: "Handler | CAT2 | SV-220660 | IP Source Guard | Voice | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220660r929001_remediate_voice: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000140_voice_Fail"

- name: "Handler | CAT2 | SV-220660 | IP Source Guard | Voice | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220660r929001_remediate_voice: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000140_voice_Pass"

- name: "Handler | CAT2 | SV-220661 | DAI | Flag for Remediation"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220661r929003_remediate_dai: true"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000150_Fail"

- name: "Handler | CAT2 | SV-220661 | DAI | Flag for Success"
  ansible.builtin.lineinfile:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_remediate.yaml"
    line: "SV_220661r929003_remediate_dai: false"
    create: yes
  delegate_to: localhost
  listen: "cat2_cisc_l2_000150_Pass"



