---
- name: |
   'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Include Tasks'
  ansible.builtin.include_tasks: "{{ item }}"
  loop: 
   - cat1_step1_8021x_access_interfaces.yml
   - cat1_step1_8021x_voice_interfaces.yml
   - cat1_step2_8021x_auth.yml
   - cat1_step3_radius_server.yml
  when:
      - SV_220649r863283
  tags:
      - CISC-L2-000020
      - SV-220649r863283
      - CAT1
      - SRG-NET-000148-L2S-000015
      - V-220649

 