---
- name: |
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 2 | Verify that 802.1x authentication is configured for the switch
     Render configuration for 802.1x access interfaces'
  ansible.builtin.template:
    src: templates/cat1/auth.j2
    dest: "/tmp/{{ inventory_hostname }}_auth.cfg"
  delegate_to: localhost
  
- name: |
   'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Step: 2 | Verify that 802.1x authentication is configured for the switch
    show run interface'
  cisco.ios.ios_command:
   commands:
    - 'show run | s {{ iosstig_radius_group_name }}'
  register: auth8021x
  
- name: |
    'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
     Step: 2 | Verify that 802.1x authentication is configured for the switch
     DIFF'
  ansible.utils.fact_diff:
      before: "{{ auth8021x.stdout[0] }}"
      after: "{{ lookup('file', '/tmp/{{ inventory_hostname }}_auth.cfg') }}"
  delegate_to: localhost
  diff: true
  register: auth_diff_result
  changed_when: auth_diff_result.diff_text | regex_findall('^\\+[^+].*$', multiline=True) 
  notify: "cat1_cisc_l2_000020_Fail"

- name: >
   'Role: Evaluate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Step: 2 | Verify that 802.1x authentication is configured for the switch
    Trigger handler if NO DIFF occurred'
  debug:
    msg: "No changes detected, notifying handler that Rule ID: SV-220649r863283 Passed"
  # Trigger this only if the previous task did NOT change
  when: not auth_diff_result.changed
  changed_when: true
  notify: "cat1_cisc_l2_000020_Pass"
  

 