---
- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220650 | Rule ID: SV-220650r539671 | STIG ID: CISC-L2-000030 | SRG ID: SRG-NET-000168-L2S-000019
          Step 1 | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Get VTP Mode'
  cisco.ios.ios_command:
      commands: 
        - Show vtp status | include VTP Operating Mode
  register: cisc_l2_000030_vtp_mode

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220650 | Rule ID: SV-220650r539671 | STIG ID: CISC-L2-000030 | SRG ID: SRG-NET-000168-L2S-000019
          Step 2 | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Check operating mode is not off'
  cisco.ios.ios_command:
      commands: 
          - show vtp password
  register: cisc_l2_000030_vtppassword
  when: '"VTP Operating Mode                : Off" not in cisc_l2_000030_vtp_mode.stdout'
  notify: "cat2_cisc_l2_000030_Fail" 
  changed_when: '"VTP Operating Mode                : Off" not in cisc_l2_000030_vtp_mode.stdout'

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220650 | Rule ID: SV-220650r539671 | STIG ID: CISC-L2-000030 | SRG ID: SRG-NET-000168-L2S-000019
          Step 2 | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Check operating mode is not off'
  cisco.ios.ios_command:
      commands: 
          - show vtp password
  register: cisc_l2_000030_vtppassword
  when: '"VTP Operating Mode                : Off" in cisc_l2_000030_vtp_mode.stdout'
  notify: "cat2_cisc_l2_000030_Pass"
  changed_when: '"VTP Operating Mode                : Off" in cisc_l2_000030_vtp_mode.stdout'


