---
- name: |
    'Role: Evaluate | 
    Create Directory for CKLB files
  ansible.builtin.file:
    path: "{{ cklb_path }}"
    state: directory
    owner: "{{ cklb_user }}"
    group: "{{ cklb_user }}"
  run_once: true
  delegate_to: "{{ cklb_server }}"
  vars:
    ansible_connection: ssh
    ansible_user: "{{ cklb_user }}"
    ansible_password: "{{ cklb_password }}"
    ansible_become_pass: "{{ cklb_become_pass }}"
    become: true
  when: stig_viewer == true

- name: "Role: Evaluate | GIT Retrieve"
  ansible.scm.git_retrieve:
    origin:
      url: "{{ git_url }}"
    parent_directory: /tmp
    branch:
        name: main
        duplicate_detection: no  
  register: repository
  delegate_to: localhost
  no_log: true
  run_once: true

- name: "Role: Evaluate | Handler | Delete Files"
  ansible.builtin.file:
    path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}/iosstig_{{ item }}.yaml"
    state: absent
  delegate_to: localhost
  loop:
   - remediate
   - scoped

- name: |
      'Role: Evaluate | Handler
       Push repository'
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
  run_once: true
  delegate_to: localhost

- name: Include CAT 1 evaluate
  import_tasks: cat1/cat1.yml
  when: iosl2sstig_cat1_evaluate
  tags:
      - CAT1

- name: Include CAT 2 evaluate
  import_tasks: cat2/cat2.yml
  when: iosl2sstig_cat2_evaluate
  tags:
      - CAT2

- name: Include CAT 3 evaluate
  import_tasks: cat3/cat3.yml
  when: iosl2sstig_cat3_evaluate
  tags:
      - CAT3
