---
- name: |
   'Role: Remediate | Severity: High (Cat I) | Group ID: V-220649 | Rule ID: SV-220649r863283 | STIG ID: CISC-L2-000020 | SRG ID: SRG-NET-000148-L2S-000015
    Tasks to remediate STIG configuration'
  cisco.ios.ios_config:
    src: templates/cat1/remediate.j2
  when:
      - SV_220649r863283_remediate



