---
- name: Include CAT 1 remediate
  import_tasks: cat1.yml
  when: iosl2sstig_cat1_remediate
  tags:
      - CAT1
      - high

- name: Include CAT 2 remediate
  import_tasks: cat2.yml
  when: iosl2sstig_cat2_remediate
  tags:
      - CAT2
      - medium

- name: Include CAT 3 remediate
  import_tasks: cat3.yml
  when: iosl2sstig_cat3_remediate
  tags:
      - CAT3
      - low
