---
# CISC-L2-000040 Denial of Service Prevention
- name: >
        'Role: Remediate | QoS | Severity: Medium (Cat II) | Group ID: V-220651 
         | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 
         | DOS QoS'
  cisco.ios.ios_config:
    src: 'templates/cat2/remediate_dos_qos.j2'
  when: SV_220651r1107171_remediate_qos == true

- name: >
         'Role: Remediate | Severity: Medium (Cat II) | Group ID: V-220651 
         | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 
         | DOS Access'
  cisco.ios.ios_config:
    src: 'templates/cat2/remediate_dos_access_interfaces.j2'
  when: SV_220651r1107171_remediate_access == true

- name: >
         'Role: Remediate | Severity: Medium (Cat II) | Group ID: V-220651 
         | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 
         | DOS Voice'
  cisco.ios.ios_config:
    src: 'templates/cat2/remediate_dos_voice_interfaces.j2'
  when: SV_220651r1107171_remediate_voice == true

- name: > 
         'Role: Remediate | Severity: Medium (Cat II) | Group ID: V-220651 
         | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 
         | DOS Trunk'
  cisco.ios.ios_config:
    src: 'templates/cat2/remediate_dos_trunk_interfaces.j2'
  when: SV_220651r1107171_remediate_trunk == true
