---
# CISC-L2-000200 - Static Trunks / DTP Remediation
- name: 'Role: Remediate | DTP | SV-220666 | Trunk Ports'
  cisco.ios.ios_config:
    src: 'templates/cat2/remediate_dtp_trunk.j2'
  when: SV_220666r539671_remediate_dtp == true
