---
- name: 'Role: Remediate | Severity: Medium (Cat II) | Group ID: V-220651 
         | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS'
  cisco.ios.ios_config:
    src: 'templates/cat2/dos_remediate.j2'
    save_when: 'always'
  when: SV_220651r1107171_remediate == true
