- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Get Running Configuration'
  cisco.ios.ios_command:
    commands:
      - show running-config | section policy-map QOS_POLICY_SWITCHPORT
  register: qos_running_config

- name:  'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
      QOS Audit |
     Create clean configuration string'
  ansible.builtin.set_fact:
    access_config: |
      {% for line in qos_running_config.stdout[0].splitlines() %}
      {% if line.strip() and line.strip() != '!' %}{{ line.strip() }}
      {% endif %}
      {% endfor %}
  delegate_to: localhost

- name: >
     'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
      QOS Audit |
     Trim final result'
  ansible.builtin.set_fact:
   combined_access_config: "{{ access_config | trim }}"
  delegate_to: localhost

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Compare Running Config to STIG Standard | +after indicates DIFF failures'
  ansible.utils.fact_diff:
    before: "{{ combined_access_config }}"
    after: "{{ ios_qos_standard }}"
  register: qos_diff_result
  diff: true
  changed_when: >
    qos_diff_result.diff_text | length > 0 and 
    "No newline at end of file" not in qos_diff_result.diff_text
  notify: "cat2_cisc_l2_000040_Fail"

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
        QOS Audit'
  ansible.builtin.debug: 
    msg: '{{ qos_diff_result.diff_text }}'
  when: qos_diff_result.diff_text | length > 0
 
- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
    Trigger handler if NO compliance violation occurred'
  debug:
    msg: "No changes detected for | DOS | QoS |, notifying handler that Rule ID: SV-220651r1107171 Passed"
  # Trigger this only if the previous task did NOT change
  when: not qos_diff_result.changed
  changed_when: true
  notify: "cat2_cisc_l2_000040_Pass"






