---
- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220650
      | Rule ID: SV-220650r539671 | STIG ID: CISC-L2-000030 | SRG ID: SRG-NET-000168-L2S-000019 | VTP Password"
  ansible.builtin.include_tasks: cat2_vtp_eval.yml
  when:
      - SV_220650r539671
  tags:
      - SV_220650r539671
      - CISC-L2-000030
      - CAT2
      - SRG-NET-000168-L2S-000019
      - SV-220624r539671
      - V-220650

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651
      | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
      - cat2_dos_qos_eval.yml
      - cat2_dos_access_eval.yml
      - cat2_dos_voice_eval.yml
      - cat2_dos_trunk_eval.yml
  when:
      - SV_220651r1107171
  tags:
      - SV_220651r1107171
      - CISC-L2-000040
      - CAT2
      - SRG-NET-000193-L2S-000020
      - SV-220651r1107171_rule
      - V-220651

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656
      | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | BPDU Guard"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
      - cat2_bpdu_access_eval.yml
      - cat2_bpdu_voice_eval.yml
  when:
      - SV_220656r856278
  tags:
      - SV_220656r856278
      - CISC-L2-000100
      - CAT2
      - SRG-NET-000362-L2S-000022
      - SV-220656r856278_rule
      - V-220656

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220657
      | Rule ID:SV-220657r856279 | STIG ID: CISC-L2-000110 | SRG ID: SRG-NET-000362-L2S-000023 | STP Loop Guard"
  ansible.builtin.include_tasks: cat2_stp_loop_eval.yml
  when: SV_220657r856279
  tags:
      - SV_220657r856279
      - CISC-L2-000110
      - CAT2
      - SRG-NET-000362-L2S-000023
      - SV_220657r856279

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220658
      | Rule ID: SV-220658r856280 | STIG ID: CISC-L2-000120 | SRG ID: SRG-NET-000362-L2S-000024 | UUFB"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
      - cat2_uufb_access_eval.yml
      - cat2_uufb_voice_eval.yml
  when:
      - SV_220658r856280
  tags:
      - SV_220658r856280
      - CISC-L2-000120
      - CAT2
      - SRG-NET-000362-L2S-000024
      - SV_220658r856280

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220659 | Rule ID: SV-220659r928999 | STIG ID: CISC-L2-000130 | SRG-NET-000362-L2S-000025 |
      DHCP Snooping"
  ansible.builtin.include_tasks: cat2_dhcp_snooping_eval.yml
  when:
      - SV_220659r928999
  tags:
      - SV_220659r928999
      - CISC-L2-000130
      - CAT2
      - SRG-NET-000362-L2S-000025
      - SV_220659r928999

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220660 | Rule ID:SV-220660r929001 | STIG ID: CISC-L2-000140 | SRG ID: SRG-NET-000362-L2S-000026 |
      Access | IP Source Guard"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
      - cat2_ipsg_access_eval.yml
      - cat2_ipsg_voice_eval.yml
  when:
      - SV_220660r929001
  tags:
      - SV_220660r929001
      - CISC-L2-000140
      - CAT2
      - SRG-NET-000362-L2S-000026
      - SV_220660r929001

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220661
      | Rule ID: SV-220661r929003 | STIG ID: CISC-L2-000150 | SRG ID: SRG-NET-000362-L2S-000027 | DAI"
  ansible.builtin.include_tasks: cat2_dai_eval.yml
  when:
      - SV_220661r929003
  tags:
      - SV_220661r929003
      - CISC-L2-000150
      - CAT2
      - SRG-NET-000362-L2S-000027
      - V-220661

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220664
      | Rule ID: SV-220664r539671 | STIG ID: CISC-L2-000180 | SRG ID: SRG-NET-000512-L2S-000003 | STP Mode"
  ansible.builtin.include_tasks: cat2_stp_mode_eval.yml
  when:
      - SV_220664r539671
  tags:
      - SV_220664r539671
      - CISC-L2-000180
      - CAT2
      - SRG-NET-000512-L2S-000003
      - V-220664

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220665
      | Rule ID: SV-220665r539671 | STIG ID: CISC-L2-000190 | SRG ID: SRG-NET-000512-L2S-000004 | UDLD"
  ansible.builtin.include_tasks: cat2_udld_eval.yml
  when:
      - SV_220665r539671
  tags:
      - SV_220665r539671
      - CISC-L2-000190
      - CAT2
      - SRG-NET-000512-L2S-000004
      - V-220665

- name: "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220666
      | Rule ID: SV-220666r539671 | STIG ID: CISC-L2-000200 | SRG ID: SRG-NET-000512-L2S-000005 | Static Trunks / DTP"
  ansible.builtin.include_tasks: cat2_dtp_eval.yml
  when:
      - SV_220666r539671
  tags:
      - SV_220666r539671
      - CISC-L2-000200
      - CAT2
      - SRG-NET-000512-L2S-000005
      - V-220666

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220667 | Rule ID: SV-220667r991904 |
      STIG ID: CISC-L2-000210 | SRG-NET-000512-L2S-000007 | Unused Port Blackhole"
  ansible.builtin.include_tasks: cat2_blackhole_eval.yml
  when: SV_220667r991904
  tags:
      - SV_220667r991904
      - CISC-L2-000210
      - CAT2
      - SRG-NET-000512-L2S-000007
      - V-220667

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220668 | Rule ID: SV-220668r991905 | STIG ID: CISC-L2-000220 | SRG-NET-000512-L2S-000008
      | VLAN 1 No Access Ports"
  ansible.builtin.include_tasks: cat2_vlan1_eval.yml
  when: SV_220668r991905
  tags:
      - SV_220668r991905
      - CISC-L2-000220
      - CAT2
      - SRG-NET-000512-L2S-000008
      - V-220668

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220669 | Rule ID: SV-220669r991906 | STIG ID: CISC-L2-000230 | SRG-NET-000512-L2S-000009 |
      VLAN 1 Trunk Pruning"
  ansible.builtin.include_tasks: cat2_vlan1_trunk_eval.yml
  when: SV_220669r991906
  tags:
      - SV_220669r991906
      - CISC-L2-000230
      - CAT2
      - SRG-NET-000512-L2S-000009 |
      - V-220669

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220670 | Rule ID: SV-220670r991907 | STIG ID: CISC-L2-000240 | SRG-NET-000512-L2S-000010 |
      Management VLAN Check"
  ansible.builtin.include_tasks: cat2_vlan1_mgmt_eval.yml
  when: SV_220670r991907
  tags:
      - SV_220670r991907
      - CISC-L2-000240
      - CAT2
      - SRG-NET-000512-L2S-000010
      - V-220670

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220671 | Rule ID: SV-220671r991908 | STIG ID: CISC-L2-000250 | SRG-NET-000512-L2S-000011 |
      User-Facing Port Mode"
  ansible.builtin.include_tasks: cat2_user_port_eval.yml
  when: SV_220671r991908
  tags:
      - SV_220671r991908
      - CISC-L2-000250
      - CAT2
      - SRG-NET-000512-L2S-000011
      - V-220671

- name:
      "Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220672 | Rule ID: SV-220672r991909 | STIG ID: CISC-L2-000260 | SRG-NET-000512-L2S-000012 |
      Native VLAN ID"
  ansible.builtin.include_tasks: cat2_vlan1_trunk_native_eval.yml
  when: SV_220672r991909
  tags:
      - SV_220672r991909
      - CISC-L2-000260
      - CAT2
      - SRG-NET-000512-L2S-000012
      - V-22067
