---
- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220657 | SV-220657r856279 | STIG ID: CISC-L2-000110 | SRG-NET-000362-L2S-000023 |
         STP Loop Guard | Get Running Configuration'
  cisco.ios.ios_command:
    commands:
      - show running-config | include spanning-tree loopguard default
  register: stp_loop_config

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220657 | SV-220657r856279 | STIG ID: CISC-L2-000110 | SRG-NET-000362-L2S-000023 |
         STP Loop Guard |  Create clean configuration string'
  ansible.builtin.set_fact:
    stp_loop_current: "{{ stp_loop_config.stdout[0] | trim }}"
  delegate_to: localhost

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220657 | SV-220657r856279 | STIG ID: CISC-L2-000110 | SRG-NET-000362-L2S-000023 |
         STP Loop Guard | Output indicates the missing STP Loop Guard command'
  ansible.utils.fact_diff:
    before: "{{ stp_loop_current }}"
    after: "spanning-tree loopguard default"
  register: stp_loop_diff
  delegate_to: localhost
  diff: true
  changed_when: stp_loop_diff.diff_text | length > 0
  notify: "cat2_cisc_l2_000110_Fail"

- name: 'Role: Evaluate | CAT II | SV-220631 | STP Loop Guard | Trigger Pass Handler'
  ansible.builtin.debug:
    msg: "STP Loop Guard is correctly enabled."
  when: not stp_loop_diff.changed
  changed_when: true
  notify: "cat2_cisc_l2_000110_Pass"
