---
# CISC-L2-000100 - BPDU Guard Evaluation
- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Access BPDU Guard
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_access_ports }}"
  loop_control:
    loop_var: show_item
  register: access_bpdu

- name: >
     'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Access BPDU Guard
     Create clean configuration string'
  ansible.builtin.set_fact:
   missing_bpdu_interfaces: >-
      {{ access_bpdu.results | 
         selectattr('stdout', 'defined') | 
         rejectattr('stdout.0', 'search', 'spanning-tree bpduguard enable') | 
         map(attribute='show_item.name') | list 
         | unique }}
  delegate_to: localhost
  changed_when: missing_bpdu_interfaces | length > 0
  notify: "cat2_cisc_l2_000100_access_Fail"

- name: "STIG | Show findings | bpdu | Access "
  ansible.builtin.debug:
    msg: "The following interfaces are non-compliant: {{ missing_bpdu_interfaces }}"
  when: missing_bpdu_interfaces | length > 0
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Access BPDU Guard
    Trigger handler if NO DIFF occurred'
  debug:
    msg: "No compliance violation detected for | BPDU | Access, notifying handler that Rule ID: SV-220656r856278 Passed"
  when: missing_bpdu_interfaces | length == 0
  changed_when: true
  notify: "cat2_cisc_l2_000100_access_Pass"

