---
- name: >
   'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_trunk_ports }}"
  loop_control:
    loop_var: show_item
  register: trunk_dos

- name: >
     'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
     Create clean configuration string'
  ansible.builtin.set_fact:
      missing_dos_trunk: >-
        {{ trunk_dos.results | 
          selectattr('stdout', 'defined') | 
          rejectattr('stdout.0', 'search', 'service-policy output QOS_POLICY_SWITCHPORT') | 
          map(attribute='show_item.name') | list 
          | unique }}
  delegate_to: localhost
  changed_when: missing_dos_voice | length > 0
  notify: "cat2_cisc_l2_000040_trunk_Fail"
 
- name: "STIG | Show findings | DOS | Trunk"
  ansible.builtin.debug:
    msg: "The following interfaces are non-compliant: {{ missing_dos_trunk }}"
  when: missing_dos_trunk | length > 0

- name: >
   'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
    Trigger handler if NO compliance violation occurred'
  debug:
    msg: "No changes detected for | DOS | Trunk, notifying handler that Rule ID: SV-220651r1107171 Passed"
  # Trigger this only if the previous task did NOT change
  when: missing_dos_trunk | length == 0
  changed_when: true
  notify: "cat2_cisc_l2_000040_trunk_Pass"

