---
# CISC-L2-000140 - IP Source Guard Evaluation
- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220660 | Rule ID:SV-220660r929001 | STIG ID: CISC-L2-000140 | SRG ID: SRG-NET-000362-L2S-000026 | Access | IP Source Guard
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_access_ports }}"
  loop_control:
    loop_var: show_item
  register: access_ipsg

- name: >
     'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220660 | Rule ID:SV-220660r929001 | STIG ID: CISC-L2-000140 | SRG ID: SRG-NET-000362-L2S-000026 | Access | IP Source Guard
     Create clean configuration string'
  ansible.builtin.set_fact:
   missing_ipsg_interfaces: >-
      {{ access_ipsg.results | 
         selectattr('stdout', 'defined') | 
         rejectattr('stdout.0', 'search', 'ip verify source') | 
         map(attribute='show_item.name') | list 
         | unique }}
  delegate_to: localhost
  changed_when: missing_ipsg_interfaces | length > 0
  notify: "cat2_cisc_l2_000140_access_Fail"

- name: "STIG | Show findings | ipsg | Access "
  ansible.builtin.debug:
    msg: "The following interfaces are non-compliant: {{ missing_ipsg_interfaces }}"
  when: missing_ipsg_interfaces | length > 0
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220660 | Rule ID:SV-220660r929001 | STIG ID: CISC-L2-000140 | SRG ID: SRG-NET-000362-L2S-000026 | Access | IP Source Guard
    Trigger handler if NO compliance violation occurred'
  debug:
    msg: "No compliance violation detected for | IPSG | Access, notifying handler that Rule ID: SV-220660r929001  Passed"
  when: missing_ipsg_interfaces | length == 0
  changed_when: true
  notify: "cat2_cisc_l2_000140_access_Pass"

