---
# CISC-L2-000240 - Management VLAN Evaluation
# This task ensures the default VLAN (VLAN 1) is not used for in-band management traffic.

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220670 | Rule ID: SV-220670r991907 | STIG ID: CISC-L2-000240 |
    Management VLAN | Get Interface IPv4 Facts'
  cisco.ios.ios_command:
    commands:
      - show ip interface brief | include ^Vlan
  register: vlan_ips_out

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220670 | Rule ID: SV-220670r991907 | STIG ID: CISC-L2-000240 |
        Management VLAN | Identify VLAN 1 Management'
  ansible.builtin.set_fact:
    vlan1_mgmt_finding: >-
      {%- set finding = [] -%}
      {%- set output = vlan_ips_out.stdout[0] -%}
      {# Check if Vlan1 has an IP assigned (not 'unassigned') #}
      {%- if 'Vlan1' in output and 'unassigned' not in output.split('Vlan1')[1].split('\n')[0] -%}
        {%- set _ = finding.append('Vlan1') -%}
      {%- endif -%}
      {{ finding }}
  delegate_to: localhost

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220670 | Rule ID: SV-220670r991907 | STIG ID: CISC-L2-000240 |
        | Trigger Fail'
  ansible.builtin.debug:
    msg: "VLAN 1 is being used for Management IP. Rule ID: SV-220670r991907 Failed."
  when: vlan1_mgmt_finding | length > 0
  changed_when: true
  notify: "cat2_cisc_l2_000240_Fail"

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220670 | Rule ID: SV-220670r991907 | STIG ID: CISC-L2-000240 | SRG-NET-000512-L2S-000010 |
    Management VLAN | Trigger Pass'
  ansible.builtin.debug:
    msg: "No compliance violation detected for | Management VLAN |, notifying handler that Rule ID: SV-220670r991907 Passed"
  when: vlan1_mgmt_finding | length == 0
  changed_when: true
  notify: "cat2_cisc_l2_000240_Pass"
