---
- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Voice BPDU Guard
     show run interface'
  cisco.ios.ios_command:
    commands:
      - 'show run int {{ show_item.name }} | exclude Building configuration...|Current configuration'
  loop: "{{ iosstig_voice_ports }}"
  loop_control:
    loop_var: show_item
  register: voice_bpdu

- name: >
     'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Voice BPDU Guard
     Create clean configuration string'
  ansible.builtin.set_fact:
      missing_bpdu_voice: >-
        {{ voice_bpdu.results | 
          selectattr('stdout', 'defined') | 
          rejectattr('stdout.0', 'search', 'spanning-tree bpduguard enable') | 
          map(attribute='show_item.name') | list 
          | unique }}
  delegate_to: localhost
  changed_when: missing_bpdu_voice | length > 0
  notify: "cat2_cisc_l2_000100_voice_Fail"

- name: "STIG | Show findings | bpdu | Voice "
  ansible.builtin.debug:
    msg: "The following interfaces are non-compliant: {{ missing_bpdu_voice }}"
  when: missing_bpdu_voice | length > 0
  delegate_to: localhost

- name: >
    'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220656 | Rule ID:SV-220656r856278 | STIG ID: CISC-L2-000100 | SRG ID: SRG-NET-000362-L2S-000022 | Voice BPDU Guard
    Trigger handler if NO compliance violation occurred'
  debug:
    msg: "No compliance violation detected, notifying handler that Rule ID: SV-220656r856278 Passed"
  # Trigger this only if the previous task did NOT change
  when: missing_bpdu_voice | length == 0
  changed_when: true
  notify: "cat2_cisc_l2_000100_voice_Pass"

