- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Get Running Configuration'
  cisco.ios.ios_command:
    commands:
      - show running-config | section class-map|policy-map QOS_POLICY_SWITCHPORT
  register: qos_running_config

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Compare Running Config to STIG Standard'
  ansible.utils.fact_diff:
    before: "{{ qos_running_config.stdout[0] }}"
    after: "{{ ios_qos_standard }}"
  register: qos_diff_result

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Trigger Failure'
  ansible.builtin.debug:
    msg: "STIG Violation: QoS Class-maps or Policy-map do not match the required bandwidth/DSCP values."
  when: qos_diff_result.diff_text | length > 0
  notify:  "cat2_cisc_l2_000040_Fail"
  changed_when: true

- name: 'Role: Evaluate | Severity: Medium (Cat II) | Group ID: V-220651 | Rule ID:SV-220651r1107171 | STIG ID: CISC-L2-000040 | SRG ID: SRG-NET-000193-L2S-000020 | DOS
         QOS Audit | Trigger Pass'
  ansible.builtin.debug:
    msg: "QoS configuration is compliant with STIG requirements."
  when: qos_diff_result.diff_text | length == 0
  notify: "cat2_cisc_l2_000040_Pass"
  changed_when: true
