---
- name: 'Role: Remediate | SV-220663 | IGMP Snooping | Apply Corrective Config'
  cisco.ios.ios_config:
    src: templates/cat3/remediate_igmp_snooping.j2
  when: SV_220663_remediate_igmp == true
