---
- name: 'Role: Remediate | Severity: Low (Cat III) | SV-220662 | Storm Control | Apply Configuration'
  cisco.ios.ios_config:
    src: templates/cat3/remediate_storm_control.j2
  when: SV_220662r648766_remediate_storm == true
