---
# CISC-L2-000270 - Native VLAN Tagging Evaluation
# This task verifies that the native VLAN is tagged on all trunks to prevent VLAN hopping attacks.
- name: 'Role: Evaluate | Severity: Low (Cat III) | Group ID: V-220673 | Rule ID: SV-220673r991910 | STIG ID: CISC-L2-000270 | Access Native VLAN | Initialize Finding Lists'
  ansible.builtin.set_fact:
    access_native_violators: []

- name: 'Role: Evaluate | Severity: Low (Cat III) | Group ID: V-220673 | Rule ID: SV-220673r991910 | STIG ID: CISC-L2-000270 | Access Native VLAN | Identify Violations'
  ansible.builtin.set_fact:
    access_native_violators: >-
      {%- set violators = [] -%}
      {%- for port in iosstig_access_ports | default([]) -%}
        {# Check if the access VLAN matches the defined Native VLAN #}
        {%- if port.access.vlan | string == iosstig_native_vlan | string -%}
          {%- set _ = violators.append({'name': port.name, 'vlan': port.access.vlan}) -%}
        {%- endif -%}
      {%- endfor -%}
      {{ violators }}
  delegate_to: localhost

- name: 'Role: Evaluate | Severity: Low (Cat III) | Group ID: V-220673 | Rule ID: SV-220673r991910 | STIG ID: CISC-L2-000270 | Access Native VLAN | Trigger Fail'
  ansible.builtin.debug:
    msg: "Access ports assigned to Native VLAN: {{ access_native_violators }}"
  when: access_native_violators | length > 0
  changed_when: true
  notify: "cat3_cisc_l2_000270_Fail"

- name: 'Role: Evaluate | Severity: Low (Cat III) | Group ID: V-220673 | Rule ID: SV-220673r991910 | STIG ID: CISC-L2-000270 | Access Native VLAN | Trigger Pass'
  ansible.builtin.debug:
    msg: "No access ports are assigned to the Native VLAN. Rule ID: SV-220673r991910 Passed."
  when: access_native_violators | length == 0
  changed_when: true
  notify: "cat3_cisc_l2_000270_Pass"
